# -*- coding: utf-8 -*-
"""Nhan Dien Khuon Mat

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YOB3TAP9KGsPqeUcdXp3sKl4h4ylQXAN
"""

pip install mtcnn

import matplotlib.pyplot as plt
from mtcnn import MTCNN

filename = 'test.jpg'
pixel = plt.imread(filename)
detector = MTCNN()
faces = detector.detect_faces(pixel)


data = plt.imread(filename)
plt.imshow(data)
ax = plt.gca()

for face in faces:
  x,y,width,height = face['box']
  rect = plt.Rectangle((x,y),width,height,fill=False,color='red')
  ax.add_patch(rect)
plt.show()

draw_faces(filename, faces)